analise_task:
  description: |
    Identify the main theme, objectives, GAP, results, limitations, conclusions, future recommendations, suggestions for improvements, detailed criticisms and specific improvements of the document.
   Use the following prompts:
    0 - THEME: Identify the main theme of the document.
    1 - OBJECTIVES: Identify the main objectives of this page of the document and summarize them in a clear and concise paragraph.
    2 - GAP: Identify the GAP addressed on this page of the document and summarize it in a clear paragraph.
    5 - RESULTS: Summarize the results presented on this page, focusing on quantitative data and suggest improvements.
    6 - LIMITATIONS: Produce a paraphrased text of the limitations presented on this page.
    7 - CONCLUSION: Summarize the conclusions presented on this page.
    8 - FUTURE: Point out recommendations for future investigations based on the conclusions on this page.
    9 - EVALUATION: Make a critical evaluation of this page, avoiding generalizations.
    10 - SUGGESTIONS: List suggestions for improvements to this page of the document.
    11 - CRITIQUES: Present detailed criticisms about this page of the document.
    12 - IMPROVEMENTS: Identify and suggest specific improvements for this page of the document.
  expected_output: 'A detailed document containing the complete analysis based on the requests provided.'
